---
# tasks file for ansible/tools
- name: Outils | Install
  apt:
    name:
      - ntp
      - rsync
      - fail2ban
      - certbot
      - ffmpeg
    state: present

- name: Outils | Latest
  apt:
    name:
      - acl
      - zip
      - unzip
      - curl
      - wget
      - make
      - git
      - vim
    state: latest
    update_cache: yes

- name: Install aptitude
  apt:
    name:
      - aptitude
    state: present
    update_cache: yes

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true
