
# config loginFormType
- name: Taiga | remove loginFormType
  lineinfile:
    path: "{{ front_config_path }}"
    firstmatch: yes
    regex: .*loginFormType.*
    state: absent
    backup: yes

- name: Taiga | add loginFormType
  lineinfile:
    path: "{{ front_config_path }}"
    firstmatch: yes
    insertafter: "{"
    line: '    "loginFormType": "{{ taiga_login_form_type }}",'
    state: present
  when: taiga_login_form_type != ""