---
# tasks file for ansible/roles/taiga
- name: Outils | Remove certbot if exists
  apt:
    name:
      - certbot
    update_cache: yes
    state: absent

- name: Taiga | Create taiga-config folder
  file:
    path: "/home/{{ ansible_user }}/taiga-config/taiga-gateway"
    state: directory
    recurse: yes
    mode: 0755

- name: Taiga SSL Config | well-known conf default
  set_fact:
    taiga_is_secure: false

- name: Taiga | docker compose template with no secure
  template:
    src: "../templates/docker-compose.yml.j2"
    dest: "/home/{{ ansible_user }}/taiga-config/docker-compose.yml"
    mode: "0755"
    force: yes

- name: Taiga | insecure conf template
  template:
    src: "../templates/taiga-insecure.conf.j2"
    dest: "/home/{{ ansible_user }}/taiga-config/taiga-gateway/taiga.conf"
    mode: "0755"
    force: yes

- name: Taiga | Docker compose create and start services
  community.docker.docker_compose:
    project_src: "/home/{{ ansible_user }}/taiga-config"
    project_name: taiga
    files:
      - docker-compose.yml
    state: present
  register: output

- debug:
    var: output

- name: Taiga | generate ssh certificate
  command: "docker-compose run --rm certbot certonly --non-interactive --agree-tos --webroot --webroot-path /var/www/certbot/ -d {{ taiga_domain }} -m {{ system_email }}"
  args:
    chdir: "/home/{{ ansible_user }}/taiga-config"
    creates: "/home/{{ ansible_user }}/taiga-config/certbot/conf/live/{{ taiga_domain }}/fullchain.pem"
  when: taiga_secure == true

- name: Taiga | taiga ssl conf template
  template:
    src: "../templates/taiga-secure.conf.j2"
    dest: "/home/{{ ansible_user }}/taiga-config/taiga-gateway/taiga.conf"
    mode: "0755"
    force: yes
  when: taiga_secure == true

- name: Taiga SSL Config | well-known conf default
  set_fact:
    taiga_is_secure: true
  when: taiga_secure == true

- name: Taiga | docker compose template with ssl enabled
  template:
    src: "../templates/docker-compose.yml.j2"
    dest: "/home/{{ ansible_user }}/taiga-config/docker-compose.yml"
    mode: "0755"
    force: yes
  when: taiga_secure == true

- name: Taiga | Docker compose recreate services
  community.docker.docker_compose:
    project_src: "/home/{{ ansible_user }}/taiga-config"
    project_name: taiga
    files:
      - docker-compose.yml
    recreate: always
  when: taiga_secure == true
