---
# tasks file for ansible/roles/mysql

- name: MySQL | Install
  apt:
    name:
      - mysql-server
      - python-mysqldb
    state: present

- name: MySQL | Set root password
  mysql_user:
    check_implicit_admin: true
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: root
    host: localhost
    password: "{{ mysql_root_password }}"
    state: present

- name: MySQL | Remove anonymous users
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: ""
    state: absent

- name: MySQL | Remove test database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: test
    state: absent
