---
# tasks file for ansible/roles/mysql

- name: Mysql | Install and dependencies
  apt:
    name:
      - mysql-server
      - mysql-client
      - mysql-common
      - libmysqlclient-dev
    state: present
    update_cache: yes

- name: MySQL | Pip Install Pymysql
  pip:
    name: pymysql
    state: absent

- name: MySQL | start and enable mysql service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Removes all anonymous user accounts
  community.mysql.mysql_user:
    name: ""
    host_all: yes
    state: absent

- name: Create database user with name 'bob' and password '12345' with all database privileges
  community.mysql.mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL"
    state: present

- name: MySQL | Remove test database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: test
    state: absent
