terminal:
  # This can be any image that has the necessary runtime environment for your project.
  image: python:3.9
  before_script:
    - apk update
  script: sleep 60
  tags:
    - global
  variables:
    RAILS_ENV: "test"
    NODE_ENV: "test"
