---
- name: "Server initialization"
  hosts: testservers
  remote_user: vagrant
  become: true
  become_method: sudo
  tasks:
    - name: Include config vars
      include_vars:
        file: "vars.yml"
    - name: APT | Update & Upgrade
      apt:
        upgrade: dist
        update_cache: yes

  roles:
    - tools
    - docker
    - nginx
    # - mysql
