---
- name: "All servers prerequisites"
  hosts: test_server
  remote_user: vagrant
  become: true
  become_method: sudo
  vars_files:
    - vars.yml
  tasks:
    - name: APT | Update & Upgrade
      apt:
        upgrade: dist
        update_cache: yes
  roles:
    - { role: tools, tags: [tools] }

- name: Test server
  hosts: test_server
  remote_user: vagrant
  become: true
  vars_files:
    - vars.yml
  roles:
    - nginx
    - mysql
    - { role: php, tags: [php, tools] }
    - { role: nodejs, tags: [nodejs, tools], vars: { pm2: false } }
    - { role: docker, when: docker }
    - { role: suitecrm, tags: [suitecrm] }
# - name: Progile server
#   hosts: progile_server
#   remote_user: ubuntu
#   vars_files:
#     - vars.yml
#   vars:
#     taiga_secure: true
#     docker: true
#   roles:
#     - { role: docker, when: docker }
#     - { role: taiga, tags: ["docker", "taiga"] }

# - name: Salesforce Server
#   hosts: salesforce_server
#   become: true
#   vars:
#     suitecrm_db_name: suitecrm
#     suitecrm_db_user: suitecrm
#     suitecrm_db_pass: suitecrm
#     suitecrm_db_host: localhost
#   vars_files:
#     - vars.yml
#   roles:
#     - nginx
#     - mysql
#     - { role: php, tags: [php, tools] }
#     - { role: suitecrm, tags: [suitecrm, tools] }
#     - { role: docker, when: docker }
