---
- name: "Server initialization"
  hosts: test_server
  remote_user: vagrant
  become: true
  become_method: sudo
  vars_files:
    - vars.yml
  tasks:
    - name: APT | Update & Upgrade
      apt:
        upgrade: dist
        update_cache: yes

  roles:
    # - tools
    # - docker
    # - nginx
    - mysql
