---
- name: "Server initialization"
  hosts: testservers
  remote_user: vagrant
  become: true
  become_method: sudo
  tasks:
    - name: APT | Update & Upgrade
      apt:
        upgrade: dist
        update_cache: yes

  roles:
    - tools
    # - mysql
