---
- name: Salesforce Server
  hosts: salesforce_server
  become: true
  vars_files:
    - vars.yml
  vars:
    suitecrm_db_name: suitecrm
    suitecrm_db_user: suitecrm
    suitecrm_db_pass: suitecrm
    suitecrm_db_host: localhost
    suitecrm_download_url: https://suitecrm.com/files/147/SuiteCRM-8.1/618/SuiteCRM-8.1.0.zip
    docker: false
  roles:
    - mysql
    - nginx
    - suitecrm
