---
- name: Progile server
  hosts: progile_server
  remote_user: ubuntu
  become: true
  vars_files:
    - vars.yml
  vars:
    taiga_secure: true
    taiga_domain: progile.icloudeng.com
    taiga_superuser_password: Platform@icloudeng.com-202109
    taiga_superuser_username: Installation
    taiga_superuser_email: installation@gmail.com
    docker: true
  pre_tasks:
    - name: APT | Update & Upgrade
      become: true
      apt:
        upgrade: dist
        update_cache: yes
  roles:
    - tools
    - firewall
    - docker
    - taiga
