---
- name: Progile server
  hosts: progile_server
  remote_user: ubuntu
  become: true
  vars_files:
    - vars.yml
  vars:
    docker: true
    taiga_secure: true
    taiga_domain: progile.icloudeng.com
    taiga_superuser_password: Platform@icloudeng.com-202109
    taiga_superuser_username: Installation
    taiga_superuser_email: installation@icloudeng.com
    # Email variables
    taiga_email_enabled: true
    taiga_email_from: "{{ taiga_superuser_email }}"
    taiga_email_host: "mail.icloudeng.com"
    taiga_email_port: 587
    taiga_email_username: "{{ taiga_superuser_email }}"
    taiga_email_password: "{{ taiga_superuser_password }}"
    taiga_email_use_tls: true
    taiga_email_use_ssl: false
    # LDAP variables
    taiga_ldap_enabled: false
    taiga_ldap_host: "ldap.icloudeng.com"
    taiga_ldap_port: 389
    taiga_ldap_use_ssl: false
    taiga_ldap_bind_dn: "cn=admin,dc=icloudeng,dc=com"
    taiga_ldap_bind_password: "{{ taiga_superuser_password }}"
    taiga_ldap_search_dn: "ou=People,dc=icloudeng,dc=com"
    taiga_ldap_search_filter: "(uid=%s)"
    taiga_ldap_user_dn_template: "uid=%s,ou=People,dc=icloudeng,dc=com"
  pre_tasks:
    - name: APT | Update & Upgrade
      become: true
      apt:
        upgrade: dist
        update_cache: yes
  roles:
    - tools
    - firewall
    - docker
    - { role: taiga, tags: taiga }
