---
- name: Progile server
  hosts: progile_server
  remote_user: taiga
  become: true
  vars_files:
    - vars.yml
  vars:
    docker: true
    # Taiga Global vars
    taiga_login_form_type: "ldap"
    taiga_public_register_enabled: false
    taiga_secret_key: "Hj5JhLCJ8J2DFotrNsH5XZi4CJfbhzzvfyuSjSMa"
    # Taiga site vars
    taiga_secure: true
    taiga_domain: progile.smatflow.net
    taiga_superuser_password: Platform@smatflow.com-202109
    taiga_superuser_username: admin
    taiga_superuser_email: taiga@smatflow.com
    # Email variables
    taiga_email_enabled: true
    taiga_email_host: "mail.smatflow.net"
    taiga_email_port: 587
    taiga_email_from: "{{ taiga_superuser_email }}"
    taiga_email_username: "{{ taiga_superuser_email }}"
    taiga_email_password: "Hj5JhLCJ8J2DFotrNsH5XZi4CJfbhzzvfyuSjSMa"
    taiga_email_use_tls: true
    taiga_email_use_ssl: false
    # LDAP variables
    taiga_ldap_enabled: true
    taiga_ldap_host: "ipa-server.smatflow.smfl"
    taiga_ldap_port: 389
    taiga_ldap_use_ssl: false
    taiga_ldap_bind_dn: "uid=admin,cn=users,cn=accounts,dc=smatflow,dc=com"
    taiga_ldap_bind_password: "ttkkytj9mgu8kqaqjr2xki42p2skw7eu"
    taiga_ldap_search_dn: "cn=accounts,dc=smatflow,dc=com"
    taiga_ldap_uid_attr: "uid"
    taiga_ldap_name_attr: "displayName"
    taiga_ldap_email_attr: "mail"
    # Gitlab variables
    taiga_gitlab_enabled: false
    taiga_gitlab_url: "https://hub.smatflow.net"
    taiga_gitlab_api_client_id: "f57dc560d030b46fb500db123ecebfa7af88ca31fa605cc14d9c2455033a909d"
    taiga_gitlab_api_client_secret: "acfbe48fd64a1f799e6037bc2942a39854b8a76bb0925fc3701fee36194c2030"
  pre_tasks:
    - name: APT | Update & Upgrade
      become: true
      apt:
        upgrade: dist
        update_cache: yes
  roles:
    - tools
    - firewall
    - docker
    - { role: taiga, tags: taiga }
