- name: Gitlab Config | ldap_enabled
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: (^\#\sgitlab_rails\[\'ldap_enabled\'\] .*)
    line: "gitlab_rails['ldap_enabled'] = true"
    backrefs: yes
    state: present
  when: gitlab_ldap_enabled == true

- name: Gitlab Config | prevent_ldap_sign_in
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: (^\#\sgitlab_rails\[\'prevent_ldap_sign_in\'\] .*)
    line: "gitlab_rails['prevent_ldap_sign_in'] = false"
    backrefs: yes
    state: present
  when: gitlab_ldap_enabled == true

- name: Gitlab Config | ldap_servers
  blockinfile:
    path: /etc/gitlab/gitlab.rb
    insertbefore: (^\#\sgitlab_rails\[\'ldap_servers\'\] .*)
    block: |
      gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'
        main: # 'main' is the GitLab 'provider ID' of this LDAP server
          label: 'LDAP'
          host: '{{ gitlab_ldap_host }}'
          port: {{ gitlab_ldap_port }}
          uid: 'uid'
          bind_dn: '{{ gitlab_ldap_bind_dn }}'
          password: '{{ gitlab_ldap_bind_password }}'
          encryption: 'plain' # "start_tls" or "simple_tls" or "plain"
          verify_certificates: false
          smartcard_auth: false
          active_directory: false
          allow_username_or_email_login: false
          lowercase_usernames: false
          block_auto_created_users: false
          base: '{{ gitlab_ldap_base_dn }}'
          user_filter: '{{ gitlab_ldap_user_filter }}'
          group_base: ''
          admin_group: ''
          #sync_ssh_keys: false
          attributes:
            username: ['uid', 'userid']
            email: ['uid', 'userid']
            name: 'uid'
            first_name: 'givenName'
            last_name: 'sn'
      EOS
    state: present
  when: gitlab_ldap_enabled == true
